### ISSUE TITLE
ign-gazebo is not able to download private models from Fuel

### ISSUE THREAD

**Issue by ahcorde** [ignitionrobotics/ign-fuel-tools#155]
ign-gazebo is not able to download private models from Fuel.

I propose to add a new field

```yaml
servers:
 - url: <url to server>
 - private-token: <token>
```

The `ServerConfig` class allows to include a key to auth with the server but it is not used.
